"""Restricted OpenAI chatbot for HFFI Terminal.

The assistant is intentionally scoped to HFFI methodology, household financial
fragility, recommendations generated by the system, and project/terminal usage.
Out-of-scope questions are refused locally before any API call.
"""
from __future__ import annotations

import os
import logging
from dataclasses import dataclass
from typing import List, Tuple

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the restricted HFFI Terminal assistant.

You may answer only questions about:
- Household Financial Fragility Index (HFFI) methodology and components
- the user's current fragility profile and risk band
- the recommendation engine's market/portfolio output and rationale
- stress testing, backtesting, validation, macro indicators used by this project
- how to use this HFFI Terminal project

You must not answer general-purpose questions, political questions, unrelated coding requests, legal/tax advice, medical advice, or individual stock-price predictions outside the system recommendation context.

Use the provided user context. Do not invent numbers. Keep answers under 220 words. For trade-related questions, explain the system output and add: "This is educational analysis, not personal financial advice.""" 

ALLOWED_KEYWORDS = {
    "hffi", "fragility", "risk", "score", "recommend", "recommendation", "portfolio", "market", "household", "stress", "drawdown", "volatility", "liquidity", "debt", "savings", "expense", "income", "macro", "inflation", "unemployment", "fed", "rate", "monte carlo", "backtest", "validation", "auc", "spy", "benchmark", "terminal", "app", "dashboard", "commodity", "commodities", "bond", "treasury", "gold", "qqq", "spy", "s&p", "confidence", "model", "probability"
}
BLOCKED_KEYWORDS = {"politics", "president", "election", "medical", "diagnose", "lawsuit", "tax filing", "homework", "recipe", "weather", "sports score"}

@dataclass
class ChatMessage:
    role: str
    content: str


def is_in_scope(message: str) -> Tuple[bool, str]:
    msg = message.lower().strip()
    if any(k in msg for k in BLOCKED_KEYWORDS):
        return False, "blocked topic"
    if any(k in msg for k in ALLOWED_KEYWORDS):
        return True, "allowed HFFI/project topic"
    return False, "not related to HFFI, recommendations, validation, or terminal usage"


def _build_context(user_state: dict) -> str:
    if not user_state:
        return "No user data provided yet."
    fr = user_state.get("fragility_result")
    macro = user_state.get("macro", {})
    plan = user_state.get("investment_plan")
    portfolio = user_state.get("portfolio_choice", "—")
    inputs = user_state.get("inputs")
    lines = ["[USER'S CURRENT HFFI PROFILE]"]
    if fr is not None:
        lines.append(f"HFFI score: {fr.score:.1f}/100 ({fr.band}); 12-month distress probability: {fr.distress_probability:.1%}")
        lines.append(f"Components: L={fr.L:.2f}, D={fr.D:.2f}, E={fr.E:.2f}, P={fr.P:.2f}, M={fr.M:.2f}, LxD={fr.interaction_LD:.2f}")
    if inputs is not None:
        lines.append(f"Income ${inputs.monthly_income:,.0f}/mo; essential expenses ${inputs.monthly_essential_expenses:,.0f}/mo; savings ${inputs.liquid_savings:,.0f}; debt ${inputs.total_debt:,.0f}; debt payment ${inputs.monthly_debt_payment:,.0f}/mo")
    if macro:
        lines.append(f"Macro: inflation {macro.get('inflation_rate', 0):.1%}, FFR {macro.get('fed_funds_rate', 0):.1%}, unemployment {macro.get('unemployment_rate', 0):.1%}, VIX {macro.get('vix', 0):.1f}")
    if plan is not None:
        lines.append(f"Investment plan: {plan.portfolio} portfolio, {plan.horizon_years}y horizon, median wealth ${plan.final_p50:,.0f}")
    lines.append(f"Recommended portfolio: {portfolio}")
    return "\n".join(lines)


def _openai_response(history: List[ChatMessage], user_state: dict, model: str | None = None) -> str:
    try:
        from openai import OpenAI
    except ImportError:
        return "[Chatbot offline — install `openai` with `pip install openai`. Using the local fallback is recommended for demos without a key.]"
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return "[Chatbot offline — no OPENAI_API_KEY set. Add it to .env or use the local rule-based fallback.]"
    client = OpenAI(api_key=api_key)
    model = model or os.getenv("OPENAI_MODEL", "gpt-4.1-mini")
    messages = [{"role": "system", "content": SYSTEM_PROMPT + "\n\n" + _build_context(user_state)}]
    messages += [{"role": m.role, "content": m.content} for m in history[-8:]]
    try:
        resp = client.chat.completions.create(model=model, messages=messages, temperature=0.2, max_tokens=450)
        return resp.choices[0].message.content or "No response generated."
    except Exception as e:
        logger.warning("OpenAI API call failed: %s", e)
        return f"[Chatbot error: {type(e).__name__}: {e}]"


def _rule_based_response(message: str, user_state: dict) -> str:
    msg = message.lower()
    fr = user_state.get("fragility_result")
    if fr is None:
        return "Fill in the household profile first; then I can explain the HFFI score and recommendations."
    if "recommend" in msg or "market" in msg or "portfolio" in msg:
        return (f"For HFFI {fr.score:.1f} ({fr.band}), the system prioritizes suitability over raw return. "
                "Stable households can receive higher-growth markets, while more stretched households are steered toward resilient assets. "
                "See the Recommendations tab for the selected market, score, and plain-language rationale. This is educational analysis, not personal financial advice.")
    if "debt" in msg:
        return f"Your debt component is D={fr.D:.2f}. Higher debt service and leverage increase HFFI and lower recommendation scores for risky markets."
    if "liquidity" in msg or "savings" in msg:
        return f"Your liquidity component is L={fr.L:.2f}; lower liquid savings relative to essential expenses increases fragility."
    if "validation" in msg or "auc" in msg or "benchmark" in msg:
        return "Use `python scripts/run_academic_validation.py` to generate walk-forward AUC folds, SPY benchmark, and recommendation backtest CSVs in `outputs/`."
    return f"Your HFFI is {fr.score:.1f} ({fr.band}). I can explain the score, its components, recommendations, validation results, or how to use the terminal."


def chat(history: List[ChatMessage], user_state: dict, prefer_api: bool = True) -> str:
    if not history:
        return "Hi — ask me about your HFFI score, recommendations, validation, or how to use this terminal."
    last_user = next((m.content for m in reversed(history) if m.role == "user"), "")
    allowed, reason = is_in_scope(last_user)
    if not allowed:
        return ("I can only answer questions about the HFFI system, household fragility, recommendations, validation, stress testing, and terminal usage. "
                f"This question was blocked because it is {reason}.")
    if prefer_api and os.getenv("OPENAI_API_KEY"):
        return _openai_response(history, user_state)
    return _rule_based_response(last_user, user_state)
